// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.184
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TimeSavers.VS
{
    static class Vsix
    {
        public const string Id = "049c7ac5-ba44-4a72-b4ee-7be7fb1b0edd";
        public const string Name = "Time Savers";
        public const string Description = @"A growing collection of small time-savers to enhance day-to-day productivity for developing with Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0.3.1";
        public const string Author = "Yann Duran";
        public const string Tags = "time savers, visual studio 2015, productivity, yannduran, yd";
    }
}
