// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.184
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TimeSavers.VS
{
    static class Vsix
    {
        public const string Id = "049c7ac5-ba44-4a72-b4ee-7be7fb1b0edd";
        public const string Name = "Visual Studio Time Savers";
        public const string Description = @"A collection of essential productivity enhancements for day-to-day developing in Visual Studio 2015.";
        public const string Language = "en-US";
        public const string Version = "0.7.0";
        public const string Author = "Yann Duran";
        public const string Tags = ">visual studio, productivity enhancements, TimeSavers, yannduran, yd";
    }
}
